#!/usr/bin/env python3
"""Build a runnable JavaScript harness from the real week3 sources.

The harness concatenates, in order:
  lib/shims.js          browser/runtime shims (TextDecoder, fetch, window, print)
  ../data.js            the shipped data module
  ../script.js          the shipped recommendation/UI module
  ../tests.js           the shipped unit suite (not loaded by index.html)
  <section files>       the verification section under test

All files are evaluated in a single scope, so the sections exercise the real
implementation rather than a copy. Nothing here is shipped with the app.
"""

import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
WEEK3 = HERE.parent.parent
LIB = HERE.parent / "lib"

WIN1252_HIGH = {
    0x80: 0x20AC, 0x82: 0x201A, 0x83: 0x0192, 0x84: 0x201E, 0x85: 0x2026,
    0x86: 0x2020, 0x87: 0x2021, 0x88: 0x02C6, 0x89: 0x2030, 0x8A: 0x0160,
    0x8B: 0x2039, 0x8C: 0x0152, 0x8E: 0x017D, 0x91: 0x2018, 0x92: 0x2019,
    0x93: 0x201C, 0x94: 0x201D, 0x95: 0x2022, 0x96: 0x2013, 0x97: 0x2014,
    0x98: 0x02DC, 0x99: 0x2122, 0x9A: 0x0161, 0x9B: 0x203A, 0x9C: 0x0153,
    0x9E: 0x017E, 0x9F: 0x0178,
}
TABLE = [WIN1252_HIGH.get(b, b) for b in range(256)]

EPILOGUE = """
loadData()
  .then(function () {
    refreshMovieIndex();
    a03Print("@@JSON@@" + JSON.stringify(a03Section()));
  })
  .catch(function (error) {
    a03Print("@@ERROR@@" + String(error) + (error && error.stack ? "\\n" + error.stack : ""));
  });
"""


def embed(text):
    return json.dumps(text)


def main():
    if len(sys.argv) < 3:
        print("usage: build_harness.py <section.js> [<section2.js> ...]", file=sys.stderr)
        return 2

    sections = [pathlib.Path(p) for p in sys.argv[1:]]
    shims = (LIB / "shims.js").read_text(encoding="utf-8")
    data_js = (WEEK3 / "data.js").read_text(encoding="utf-8")
    script_js = (WEEK3 / "script.js").read_text(encoding="utf-8")
    tests_js = (WEEK3 / "tests.js").read_text(encoding="utf-8")

    payload = {
        "win1252": TABLE,
        "uItem": (WEEK3 / "u.item").read_bytes().decode("latin-1"),
        "uData": (WEEK3 / "u.data").read_bytes().decode("latin-1"),
    }

    parts = [
        "// GENERATED by evidence/lib/build_harness.py -- do not edit.\n",
        f"var A03_WIN1252 = {json.dumps(payload['win1252'])};\n",
        f"var A03_U_ITEM = {json.dumps(payload['uItem'])};\n",
        f"var A03_U_DATA = {json.dumps(payload['uData'])};\n",
        shims,
        "\n// ---- real data.js ----\n", data_js,
        "\n// ---- real script.js ----\n", script_js,
        "\n// ---- real tests.js ----\n", tests_js,
    ]
    for section in sections:
        parts.append(f"\n// ---- {section.name} ----\n")
        parts.append(section.read_text(encoding="utf-8"))
    parts.append(EPILOGUE)

    sys.stdout.write("".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
